# author : artemis lightman
# date created : jan 3, 2023
# last modified: feb 7, 2023

# command line arguments
	# n - number of decoys
	# id - pdb id of target
	# c - chains in target

# dependencies:
	# arty.py

# input: none
# output: decoys for given target generated by hdock

##############################################################################
# generates decoys for a given target
##############################################################################

import os
from datetime import datetime
import argparse
import arty

dt_start = datetime.now()

parser = argparse.ArgumentParser(description = "this script completes generates decoys for a given target using hdock")

parser.add_argument("-n", type = int, help = "number of decoys to generate", default = 500)
parser.add_argument("-id", help = "pdb id of target", required = True)
parser.add_argument("-c", help = "chains in target", required = True)
parser.add_argument("-a", help = "sampling angle", default = 6)

args = parser.parse_args()

chain_one = args.c[0]
chain_two = args.c[1]

pdb_id = args.id

num_models = str(args.n)

receptor_pdb = "../complexes/" + pdb_id + "_" + chain_one + "_noH.pdb"
ligand_pdb = "../complexes/" + pdb_id + "_" + chain_two + "_noH.pdb"

os.mkdir(pdb_id + "_hdock")

os.system("cp hdock " + pdb_id + "_hdock/hdock")
os.system("cp createpl " + pdb_id + "_hdock/createpl")

os.chdir(pdb_id + "_hdock")
os.system("./hdock " + receptor_pdb + " " + ligand_pdb  + " -angle " + args.a  + " -out hdock.out")

os.system("./createpl hdock.out top_models.pdb -nmax " + num_models + " -complex -models")

dt = datetime.now()

str_dt = dt.strftime("%H:%M:%S on %d %B, %Y ")

str_runtime = arty.get_runtime(dt_start, dt)

print ("generate_decoys.py finished at " + str_dt + " (runtime " + str_runtime + ")")